package geo

import "strings"

// ISO 3166-1 alpha-2 codes keyed by lowercase English country name.
var nameToCode = map[string]string{
	"afghanistan":                            "AF",
	"aland islands":                          "AX",
	"albania":                                "AL",
	"algeria":                                "DZ",
	"american samoa":                         "AS",
	"andorra":                                "AD",
	"angola":                                 "AO",
	"anguilla":                               "AI",
	"antarctica":                             "AQ",
	"antigua and barbuda":                    "AG",
	"argentina":                              "AR",
	"armenia":                                "AM",
	"aruba":                                  "AW",
	"australia":                              "AU",
	"austria":                                "AT",
	"azerbaijan":                             "AZ",
	"bahamas":                                "BS",
	"bahrain":                                "BH",
	"bangladesh":                             "BD",
	"barbados":                               "BB",
	"belarus":                                "BY",
	"belgium":                                "BE",
	"belize":                                 "BZ",
	"benin":                                  "BJ",
	"bermuda":                                "BM",
	"bhutan":                                 "BT",
	"bolivia":                                "BO",
	"bolivia (plurinational state of)":       "BO",
	"bonaire, sint eustatius and saba":       "BQ",
	"bosnia and herzegovina":                 "BA",
	"botswana":                               "BW",
	"bouvet island":                          "BV",
	"brazil":                                 "BR",
	"british indian ocean territory":         "IO",
	"brunei darussalam":                      "BN",
	"brunei":                                 "BN",
	"bulgaria":                               "BG",
	"burkina faso":                           "BF",
	"burundi":                                "BI",
	"cabo verde":                             "CV",
	"cape verde":                             "CV",
	"cambodia":                               "KH",
	"cameroon":                               "CM",
	"canada":                                 "CA",
	"cayman islands":                         "KY",
	"central african republic":               "CF",
	"chad":                                   "TD",
	"chile":                                  "CL",
	"china":                                  "CN",
	"christmas island":                       "CX",
	"cocos (keeling) islands":                "CC",
	"colombia":                               "CO",
	"comoros":                                "KM",
	"congo":                                  "CG",
	"congo (democratic republic of the)":     "CD",
	"democratic republic of the congo":       "CD",
	"cook islands":                           "CK",
	"costa rica":                             "CR",
	"cote d'ivoire":                          "CI",
	"cote d ivoire":                          "CI",
	"ivory coast":                            "CI",
	"croatia":                                "HR",
	"cuba":                                   "CU",
	"curacao":                                "CW",
	"cyprus":                                 "CY",
	"czechia":                                "CZ",
	"czech republic":                         "CZ",
	"denmark":                                "DK",
	"djibouti":                               "DJ",
	"dominica":                               "DM",
	"dominican republic":                     "DO",
	"ecuador":                                "EC",
	"egypt":                                  "EG",
	"el salvador":                            "SV",
	"equatorial guinea":                      "GQ",
	"eritrea":                                "ER",
	"estonia":                                "EE",
	"eswatini":                               "SZ",
	"swaziland":                              "SZ",
	"ethiopia":                               "ET",
	"falkland islands (malvinas)":            "FK",
	"falkland islands":                       "FK",
	"faroe islands":                          "FO",
	"fiji":                                   "FJ",
	"finland":                                "FI",
	"france":                                 "FR",
	"french guiana":                          "GF",
	"french polynesia":                       "PF",
	"french southern territories":            "TF",
	"gabon":                                  "GA",
	"gambia":                                 "GM",
	"georgia":                                "GE",
	"germany":                                "DE",
	"ghana":                                  "GH",
	"gibraltar":                              "GI",
	"greece":                                 "GR",
	"greenland":                              "GL",
	"grenada":                                "GD",
	"guadeloupe":                             "GP",
	"guam":                                   "GU",
	"guatemala":                              "GT",
	"guernsey":                               "GG",
	"guinea":                                 "GN",
	"guinea-bissau":                          "GW",
	"guyana":                                 "GY",
	"haiti":                                  "HT",
	"heard island and mcdonald islands":      "HM",
	"holy see":                               "VA",
	"vatican city":                           "VA",
	"honduras":                               "HN",
	"hong kong":                              "HK",
	"hungary":                                "HU",
	"iceland":                                "IS",
	"india":                                  "IN",
	"indonesia":                              "ID",
	"iran (islamic republic of)":             "IR",
	"iran":                                   "IR",
	"iraq":                                   "IQ",
	"ireland":                                "IE",
	"isle of man":                            "IM",
	"israel":                                 "IL",
	"italy":                                  "IT",
	"jamaica":                                "JM",
	"japan":                                  "JP",
	"jersey":                                 "JE",
	"jordan":                                 "JO",
	"kazakhstan":                             "KZ",
	"kenya":                                  "KE",
	"kiribati":                               "KI",
	"korea (democratic people's republic of)": "KP",
	"north korea":                            "KP",
	"korea (republic of)":                    "KR",
	"south korea":                            "KR",
	"kuwait":                                 "KW",
	"kyrgyzstan":                             "KG",
	"lao people's democratic republic":       "LA",
	"laos":                                   "LA",
	"latvia":                                 "LV",
	"lebanon":                                "LB",
	"lesotho":                                "LS",
	"liberia":                                "LR",
	"libya":                                  "LY",
	"liechtenstein":                          "LI",
	"lithuania":                              "LT",
	"luxembourg":                             "LU",
	"macao":                                  "MO",
	"macau":                                  "MO",
	"madagascar":                             "MG",
	"malawi":                                 "MW",
	"malaysia":                               "MY",
	"maldives":                               "MV",
	"mali":                                   "ML",
	"malta":                                  "MT",
	"marshall islands":                       "MH",
	"martinique":                             "MQ",
	"mauritania":                             "MR",
	"mauritius":                              "MU",
	"mayotte":                                "YT",
	"mexico":                                 "MX",
	"micronesia (federated states of)":       "FM",
	"micronesia":                             "FM",
	"moldova (republic of)":                  "MD",
	"moldova":                                "MD",
	"monaco":                                 "MC",
	"mongolia":                               "MN",
	"montenegro":                             "ME",
	"montserrat":                             "MS",
	"morocco":                                "MA",
	"mozambique":                             "MZ",
	"myanmar":                                "MM",
	"burma":                                  "MM",
	"namibia":                                "NA",
	"nauru":                                  "NR",
	"nepal":                                  "NP",
	"netherlands":                            "NL",
	"the netherlands":                        "NL",
	"holland":                                "NL",
	"new caledonia":                          "NC",
	"new zealand":                            "NZ",
	"nicaragua":                              "NI",
	"niger":                                  "NE",
	"nigeria":                                "NG",
	"niue":                                   "NU",
	"norfolk island":                         "NF",
	"north macedonia":                        "MK",
	"macedonia":                              "MK",
	"northern mariana islands":               "MP",
	"norway":                                 "NO",
	"oman":                                   "OM",
	"pakistan":                               "PK",
	"palau":                                  "PW",
	"palestine, state of":                    "PS",
	"palestine":                              "PS",
	"panama":                                 "PA",
	"papua new guinea":                       "PG",
	"paraguay":                               "PY",
	"peru":                                   "PE",
	"philippines":                            "PH",
	"pitcairn":                               "PN",
	"poland":                                 "PL",
	"portugal":                               "PT",
	"puerto rico":                            "PR",
	"qatar":                                  "QA",
	"reunion":                                "RE",
	"romania":                                "RO",
	"russian federation":                     "RU",
	"russia":                                 "RU",
	"rwanda":                                 "RW",
	"saint barthelemy":                       "BL",
	"saint helena, ascension and tristan da cunha": "SH",
	"saint kitts and nevis":                  "KN",
	"saint lucia":                            "LC",
	"saint martin (french part)":             "MF",
	"saint pierre and miquelon":              "PM",
	"saint vincent and the grenadines":       "VC",
	"samoa":                                  "WS",
	"san marino":                             "SM",
	"sao tome and principe":                  "ST",
	"saudi arabia":                           "SA",
	"senegal":                                "SN",
	"serbia":                                 "RS",
	"seychelles":                             "SC",
	"sierra leone":                           "SL",
	"singapore":                              "SG",
	"sint maarten (dutch part)":              "SX",
	"slovakia":                               "SK",
	"slovenia":                               "SI",
	"solomon islands":                        "SB",
	"somalia":                                "SO",
	"south africa":                           "ZA",
	"south georgia and the south sandwich islands": "GS",
	"south sudan":                            "SS",
	"spain":                                  "ES",
	"sri lanka":                              "LK",
	"sudan":                                  "SD",
	"suriname":                               "SR",
	"svalbard and jan mayen":                 "SJ",
	"sweden":                                 "SE",
	"switzerland":                            "CH",
	"syrian arab republic":                   "SY",
	"syria":                                  "SY",
	"taiwan, province of china":              "TW",
	"taiwan":                                 "TW",
	"tajikistan":                             "TJ",
	"tanzania, united republic of":           "TZ",
	"tanzania":                               "TZ",
	"thailand":                               "TH",
	"timor-leste":                            "TL",
	"east timor":                             "TL",
	"togo":                                   "TG",
	"tokelau":                                "TK",
	"tonga":                                  "TO",
	"trinidad and tobago":                    "TT",
	"tunisia":                                "TN",
	"turkey":                                 "TR",
	"turkiye":                                "TR",
	"turkmenistan":                           "TM",
	"turks and caicos islands":               "TC",
	"tuvalu":                                 "TV",
	"uganda":                                 "UG",
	"ukraine":                                "UA",
	"united arab emirates":                   "AE",
	"uae":                                    "AE",
	"united kingdom":                         "GB",
	"united kingdom of great britain and northern ireland": "GB",
	"great britain":                          "GB",
	"uk":                                     "GB",
	"england":                                "GB",
	"united states":                          "US",
	"united states of america":               "US",
	"usa":                                    "US",
	"u.s.":                                   "US",
	"u.s.a.":                                 "US",
	"us":                                     "US",
	"united states minor outlying islands":   "UM",
	"uruguay":                                "UY",
	"uzbekistan":                             "UZ",
	"vanuatu":                                "VU",
	"venezuela (bolivarian republic of)":     "VE",
	"venezuela":                              "VE",
	"viet nam":                               "VN",
	"vietnam":                                "VN",
	"virgin islands (british)":               "VG",
	"virgin islands (u.s.)":                  "VI",
	"wallis and futuna":                      "WF",
	"western sahara":                         "EH",
	"yemen":                                  "YE",
	"zambia":                                 "ZM",
	"zimbabwe":                               "ZW",
}

var validCodes map[string]struct{}

func init() {
	validCodes = make(map[string]struct{}, len(nameToCode))
	for _, code := range nameToCode {
		validCodes[code] = struct{}{}
	}
}

// NormalizeCountry maps a country name or code to ISO 3166-1 alpha-2.
// Returns the uppercase code when recognized, otherwise the trimmed input
// (or "Unknown" when empty).
func NormalizeCountry(input string) string {
	trimmed := strings.TrimSpace(input)
	if trimmed == "" {
		return "Unknown"
	}

	upper := strings.ToUpper(trimmed)
	if len(upper) == 2 {
		if _, ok := validCodes[upper]; ok {
			return upper
		}
	}

	key := strings.ToLower(trimmed)
	if code, ok := nameToCode[key]; ok {
		return code
	}

	return trimmed
}

// CountryQueryValues returns ISO codes to match for a country filter query.
// Accepts either a code ("US") or full name ("United States").
func CountryQueryValues(query string) []string {
	normalized := NormalizeCountry(query)
	if normalized == "Unknown" {
		return []string{"Unknown"}
	}

	upper := strings.ToUpper(strings.TrimSpace(query))
	if len(upper) == 2 && normalized == upper {
		return []string{normalized}
	}

	// Match stored ISO code; also accept legacy full-name rows if any exist.
	return []string{normalized, strings.TrimSpace(query)}
}
