#!/usr/bin/env bash
#
# Sync TRINITY_AGENT_KEY from the dashboard DB into a controller .env snippet.
#
# Agent key flow (per master deployment):
#   1. Dashboard generates/stores agent_key in dashboard.db (dashboard_deployment).
#   2. Controller API validates POST /api/heartbeat with TRINITY_AGENT_KEY.
#   3. Agents send the same key via X-API-Key or Authorization: Bearer.
#   4. Run this script (or `make sync-agent-key`) after dashboard key generation,
#      then source the output file or set TRINITY_AGENT_KEY on the controller process.
#
# Usage:
#   make sync-agent-key
#   DASHBOARD_DB_PATH=./dashboard.db CONTROLLER_ENV_FILE=.env.controller ./scripts/sync-agent-key.sh
#
# Fallback order when dashboard DB/table/key is missing:
#   TRINITY_AGENT_KEY env → .env file → write template with generation instructions

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin${PATH:+:$PATH}"
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
# shellcheck source=scripts/lib/production-common.sh
source "$ROOT/scripts/lib/production-common.sh"

DASHBOARD_DB="${DASHBOARD_DB_PATH:-./dashboard.db}"
OUTPUT="${CONTROLLER_ENV_FILE:-.env.controller}"
ENV_SOURCE="${ENV_FILE:-.env}"

if [[ "$OUTPUT" == /etc/trinityproxy/controller.env ]] && [[ "$DASHBOARD_DB" == "./dashboard.db" ]]; then
	DASHBOARD_DB="/var/lib/trinityproxy/dashboard.db"
fi

KEY=""

read_key_from_dashboard_db() {
	local db_path="$1"
	local sqlite3_bin
	sqlite3_bin="$(production_resolve_cmd sqlite3 2>/dev/null || true)"
	if [[ -z "$sqlite3_bin" ]]; then
		return 1
	fi
	if [[ ! -f "$db_path" ]]; then
		return 1
	fi

	local table
	table="$("$sqlite3_bin" "$db_path" "SELECT name FROM sqlite_master WHERE type='table' AND name='dashboard_deployment';" 2>/dev/null || true)"
	if [[ -z "$table" ]]; then
		return 1
	fi

	local value
	value="$("$sqlite3_bin" "$db_path" "SELECT agent_key FROM dashboard_deployment WHERE id = 1;" 2>/dev/null || true)"
	value="${value//$'\r'/}"
	value="${value//$'\n'/}"
	if [[ -n "$value" ]]; then
		KEY="$value"
		return 0
	fi
	return 1
}

read_key_from_env_file() {
	local file="$1"
	if [[ ! -f "$file" ]]; then
		return 1
	fi
	local line
	line="$(grep -E '^[[:space:]]*(export[[:space:]]+)?TRINITY_AGENT_KEY=' "$file" | tail -1 || true)"
	if [[ -z "$line" ]]; then
		return 1
	fi
	KEY="${line#*TRINITY_AGENT_KEY=}"
	KEY="${KEY#"${KEY%%[![:space:]]*}"}"
	KEY="${KEY%"${KEY##*[![:space:]]}"}"
	KEY="${KEY#\"}"
	KEY="${KEY%\"}"
	KEY="${KEY#\'}"
	KEY="${KEY%\'}"
	[[ -n "$KEY" ]]
}

SOURCE=""

if read_key_from_dashboard_db "$DASHBOARD_DB"; then
	SOURCE="dashboard DB ($DASHBOARD_DB)"
elif [[ -n "${TRINITY_AGENT_KEY:-}" ]]; then
	KEY="$TRINITY_AGENT_KEY"
	SOURCE="TRINITY_AGENT_KEY environment variable"
elif read_key_from_env_file "$ENV_SOURCE"; then
	SOURCE="$ENV_SOURCE"
fi

write_snippet() {
	local key="$1"
	local source_note="$2"
	if [[ "$OUTPUT" == /etc/trinityproxy/controller.env ]]; then
		local api_key controller_url api_port db_path
		api_key="$(grep -E '^TRINITY_API_KEY=' "$OUTPUT" 2>/dev/null | tail -1 | cut -d= -f2- || true)"
		controller_url="$(grep -E '^CONTROLLER_URL=' "$OUTPUT" 2>/dev/null | tail -1 | cut -d= -f2- || true)"
		api_port="$(grep -E '^API_PORT=' "$OUTPUT" 2>/dev/null | tail -1 | cut -d= -f2- || echo "3100")"
		db_path="$(grep -E '^DB_PATH=' "$OUTPUT" 2>/dev/null | tail -1 | cut -d= -f2- || echo "/var/lib/trinityproxy/trinityproxy.db")"
		[[ -n "$api_key" ]] || api_key="$(production_random_hex)"
		[[ -n "$controller_url" ]] || controller_url="http://127.0.0.1:${api_port}"
		cat >"$OUTPUT" <<EOF
TRINITY_API_KEY=${api_key}
TRINITY_AGENT_KEY=${key}
API_PORT=${api_port}
DB_PATH=${db_path}
CONTROLLER_URL=${controller_url}
EOF
		chmod 640 "$OUTPUT" 2>/dev/null || true
		return 0
	fi
	cat >"$OUTPUT" <<EOF
# TrinityProxy controller environment (generated by scripts/sync-agent-key.sh)
# Source: ${source_note}
#
# make run-controller loads this file automatically when present.
# Manual load: source ${OUTPUT}
#
# Or add TRINITY_AGENT_KEY to scripts/trinityproxy-controller.service and restart:
#   sudo systemctl restart trinityproxy-controller
export TRINITY_AGENT_KEY=${key}
EOF
}

write_template() {
	cat >"$OUTPUT" <<'EOF'
# TrinityProxy controller environment (generated by scripts/sync-agent-key.sh)
#
# No agent key found. Each master deployment needs its own TRINITY_AGENT_KEY.
#
# Option A — generate in dashboard (recommended):
#   1. Start dashboard: make run-dashboard
#   2. Open Deploy Agent or Settings; dashboard creates dashboard_deployment.agent_key
#   3. Re-run: make sync-agent-key
#
# Option B — generate manually:
#   export TRINITY_AGENT_KEY="$(openssl rand -hex 32)"
#   make sync-agent-key
#
# Then source this file or set TRINITY_AGENT_KEY on the controller process.
# TRINITY_AGENT_KEY=
EOF
}

if [[ -n "$KEY" ]]; then
	write_snippet "$KEY" "$SOURCE"
	echo "[+] Wrote TRINITY_AGENT_KEY to $OUTPUT (from $SOURCE)"
	echo "[*] Start controller: make run-controller  (auto-loads $OUTPUT)"
	exit 0
fi

write_template
echo "[!] No agent key found — wrote template to $OUTPUT"
echo "[!] Generate a key in dashboard Settings or: export TRINITY_AGENT_KEY=\$(openssl rand -hex 32)"
exit 1
